on: [push] # push 操作执行自动化


jobs:
  run-coupons: # 任务名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
           
      - name: Setup Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '16'
          
      - name: Github Page    
        run: |
          pwd
          node ./github-page.js
